#!/bin/bash

#PBS -A nfi004
#PBS -l nodes=4
#PBS -l walltime=0:10:00
#PBS -o param_1024.out
#PBS -e param_1024.err
#PBS -N Chimera_Diffusion
#PBS -m a
#PBS -m b
#PBS -m e
#PBS -M sslattery@wisc.edu
#PBS -l gres=widow2

cd $PBS_O_WORKDIR
export MPICH_PTL_MATCH_OFF=1
date
time aprun -n 64 /ccs/proj/nfi004/uy7/builds/MCLS/Chimera/drivers/NeutronDiffusion/Chimera_Diffusion.exe --xml-in-file=param_1024.xml
