SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
  Utils           utils           SS  REQUIRED
  Mesh            mesh            SS  REQUIRED
#  Solvers         solvers         SS  REQUIRED
#  Thermal         thermal         SS  REQUIRED
  ) 

SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
